services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - n8n
    restart: unless-stopped

  app:
    build: .
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  n8n:
    image: n8nio/n8n:latest
    expose:
      - "5678"
    environment:
      - N8N_WEBHOOK_URL=https://www.atlasagent.xyz
      - N8N_HOST=www.atlasagent.xyz
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - VUE_APP_URL_BASE_API=https://www.atlasagent.xyz
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=atlas2024
      - N8N_ENCRYPTION_KEY=your-secure-encryption-key-here
      - WEBHOOK_URL=https://www.atlasagent.xyz
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
# volumes:
#   postgres_data: 